export const zones = [
  {
    id: "business",
    step: "01",
    title: "My Business",
    eyebrow: "The foundation",
    description: "Who you are, what you offer, and who your content is for.",
    prompt: "Add your story, offers, audience notes, website copy, and positioning.",
    color: "apricot",
  },
  {
    id: "voice",
    step: "02",
    title: "My Voice",
    eyebrow: "Build your voice",
    description: "No past content needed—define how you want to sound and evolve it over time.",
    prompt: "Add tone preferences, phrases you like, or examples of how you want to sound.",
    color: "blue",
  },
  {
    id: "expert",
    step: "03",
    title: "Expert Brain",
    eyebrow: "Raise the quality",
    description: "Frameworks, tutorials, research, and expert examples.",
    prompt: "Add resources that teach the AI how to do the work well.",
    color: "lemon",
  },
  {
    id: "inspiration",
    step: "04",
    title: "Ideas & Inspiration",
    eyebrow: "Your content inbox",
    description: "Dump hooks, captions, content ideas, formats, visuals, and creators you admire.",
    prompt: "Save anything useful and mark exactly what caught your attention.",
    color: "lilac",
  },
];

export const starterItems = [
  {
    id: "starter-business",
    zone: "business",
    type: "note",
    title: "Start with your business story",
    content: "Primary content goal: grow on Instagram and LinkedIn. Add what you do, who you help, and why it matters.",
    tags: ["Instagram", "LinkedIn"],
    createdAt: Date.now(),
    starter: true,
  },
  {
    id: "starter-voice",
    zone: "voice",
    type: "note",
    title: "Describe how you want to sound",
    content: "You do not need existing content. Start with a few traits—warm, direct, clever, honest, expert, playful—and phrases you would or would not say.",
    tags: ["voice builder"],
    createdAt: Date.now(),
    starter: true,
  },
  {
    id: "starter-expert",
    zone: "expert",
    type: "link",
    title: "Add a trusted framework",
    content: "Save a useful article, transcript, swipe file, or set of notes that teaches a repeatable method.",
    tags: ["framework"],
    createdAt: Date.now(),
    starter: true,
  },
  {
    id: "starter-inspiration",
    zone: "inspiration",
    type: "image",
    title: "Dump anything that sparks an idea",
    content: "Upload a screenshot, paste a caption, save a hook, or write a rough content idea. Mark the exact element you want to learn from.",
    tags: ["content inbox"],
    createdAt: Date.now(),
    starter: true,
  },
];
